### ISSUE TITLE
where is your data?

### ISSUE THREAD

**Issue by yxgzhumeng** [mnguyen0226/tsgans_cps#1]
where is your data?

**Comment by minhbtnguyen** [comment]
I don't have the license to make them public:
- BATADAL dataset can be found [here](https://www.batadal.net/data.html)
- SWAT dataset can be requested [here](https://itrust.sutd.edu.sg/itrust-labs_datasets/).

**Comment by yxgzhumeng** [comment]
Thanks
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Minh T. ***@***.***>
            
        
      
      
        
         Date 
        
        
        5/30/2023 02:03
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [mnguyen0226/tsgans_cps] where is your data? (Issue #1)
        
      
    
  

Closed #1 as completed.
